version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=otsql_db
      - MYSQL_USER=otsql_user
      - MYSQL_PASSWORD=otsql_password
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=otsql_db
      - POSTGRES_USER=otsql_user
      - POSTGRES_PASSWORD=otsql_password
  jaeger:
    image: 'jaegertracing/all-in-one:latest'
    ports:
      - 14268:14268
      - 16686:16686
